name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Executa uma vez por dia Ã  meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    steps:
      - uses: actions/checkout@v2
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: true
          SHOW_OS: true
          SHOW_LOC: true
          SHOW_PROFILE_VIEWS: true
          SHOW_COMMIT: true
